//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertsDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConcertsEntities1 : DbContext
    {
        public ConcertsEntities1()
            : base("name=ConcertsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Concerts> Concerts { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<Ticket_States> Ticket_States { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    }
}
